### ISSUE TITLE
Contract that streams tokens to NFT holder address

### ISSUE THREAD

**Issue by gawainb** [g2entgroup/creative-contracts#1]
We need a contract that uses SuperFluid flow to stream royalties to NFT owners.

**Comment by Stevewu1234** [comment]
great! let's try

**Comment by gawainb** [comment]
@Stevewu1234  I believe in you brother 😁

**Comment by Stevewu1234** [comment]
Streaming tokens to NFT holder is done. But the integrated NFT contract is needed  
https://github.com/g2entgroup/creative-contracts/commit/da14a66d6b129db6fc454b8f592154ac6d9c82ca
